stages:
  - test


before_script:
  - pip install -r requirements.txt

test_api:
  stage: test
  script:
    - python api/app.py &   # start API server
    - sleep 3               # wait for server
    - pytest tests/integration/